// <auto-generated />
using System;
using MagicVila_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVila_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240810105727_add-migration Alimentar_Vila")]
    partial class addmigrationAlimentar_Vila
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVila_API.Models.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenindad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeActualization")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfFoundation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosQuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("vilas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenindad = "",
                            DataDeActualization = new DateTime(2024, 8, 10, 12, 57, 27, 602, DateTimeKind.Local).AddTicks(5558),
                            DateOfFoundation = new DateTime(2024, 8, 10, 12, 57, 27, 602, DateTimeKind.Local).AddTicks(5543),
                            Description = "Description",
                            ImageUrl = "",
                            MetrosQuadrados = 10,
                            Name = "VilaReal",
                            Ocupantes = 10,
                            Tarifa = 10.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
